// Structured mock database for Al-Athar Portal

export const academyTracks = [
	{
		id: "tajweed",
		title: "Tajweed & Tilawah",
		description:
			"Master Quranic phonetics, makharij, and rules of recitation with live corrections.",
		icon: "bi-book",
		stats: {
			level: "Beginner to Advanced",
			duration: "12 Weeks",
			lectures: "24 Sessions",
		},
		curriculum: [
			{
				id: "m1",
				title: "Makharij & Sifat (Articulation & Characteristics)",
				description:
					"Focuses on the exit points of the Arabic letters and their phonetic features.",
				lessons: [
					{
						id: "l1",
						title: "Introduction to Articulation Points",
						duration: "45 mins",
					},
					{
						id: "l2",
						title: "Throat and Tongue Letters (Halq & Lisan)",
						duration: "60 mins",
					},
					{
						id: "l3",
						title: "The Lips and Nasal Cavity (Shafatayn & Khayshum)",
						duration: "50 mins",
					},
				],
			},
			{
				id: "m2",
				title: "Rules of Noon Sakinah & Tanween",
				description:
					"Izhar, Idgham, Iqlob, and Ikhfa definitions and applications.",
				lessons: [
					{
						id: "l4",
						title: "Understanding Noon Sakinah & Tanween",
						duration: "40 mins",
					},
					{
						id: "l5",
						title: "The Clearness (Izhar) & Insertion (Idgham)",
						duration: "60 mins",
					},
				],
			},
		],
	},
	{
		id: "tafsir",
		title: "Classical Tafsir",
		description:
			"Historical contexts, linguistic depths, and practical reflections of each Surah.",
		icon: "bi-chat-square-quote",
		stats: {
			level: "Intermediate",
			duration: "16 Weeks",
			lectures: "32 Sessions",
		},
		curriculum: [
			{
				id: "m1",
				title: "Introduction to Quranic Exegesis",
				description:
					"The sciences of Tafsir, classical commentators, and rules of interpretation.",
				lessons: [
					{
						id: "l1",
						title: "What is Tafsir? (Tafsir vs Ta'wil)",
						duration: "55 mins",
					},
				],
			},
		],
	},
	{
		id: "arabic",
		title: "Quranic Arabic",
		description:
			"Grammar (Nahw) and morphology (Sarf) geared directly to comprehending the Revelation.",
		icon: "bi-translate",
		stats: { level: "Beginner", duration: "24 Weeks", lectures: "48 Sessions" },
		curriculum: [],
	},
	{
		id: "hadith-seerah",
		title: "Seerah & Hadith",
		description:
			"Study the Prophetic character and authentic traditions (Nawawi 40, Riyad us-Saliheen).",
		icon: "bi-journal-text",
		stats: { level: "Beginner", duration: "10 Weeks", lectures: "20 Sessions" },
		curriculum: [],
	},
];

export const coursesCatalog = [
	{
		id: 1,
		title: "Fundamentals of Islam & Essential Creed",
		level: "Beginner",
		duration: "8 Weeks",
		modules: "16 Modules",
		instructor: "Ustadha Amina",
		avatar: "AM",
		category: "Fundamentals & Aqeedah",
		arabicTag: "العَقِيدَةُ",
		icon: "bi-compass",
		description:
			"Comprehensive study of the Pillars of Faith (Arkan al-Iman), classical Tahawiyyah principles, and core Islamic worldview essentials.",
		detailsLink: "/courses/tajweed",
	},
	{
		id: 2,
		title: "History of Islamic Civilization: Madinah to Cordoba",
		level: "Intermediate",
		duration: "10 Weeks",
		modules: "20 Modules",
		instructor: "Dr. Hassan Said",
		avatar: "HS",
		category: "History (Tarikh)",
		arabicTag: "التَّارِيخُ",
		icon: "bi-hourglass-split",
		description:
			"Chronological survey of the Rightly Guided Caliphs, Umayyad & Abbasid eras, scientific breakthroughs, and the Golden Age of Andalusia.",
		detailsLink: "#",
	},
	{
		id: 3,
		title: "Adab & Akhlaq: Prophetic Ethics & Character",
		level: "All Levels",
		duration: "6 Weeks",
		modules: "12 Modules",
		instructor: "Shaykh Zayd Ali",
		avatar: "ZA",
		category: "Adab & Akhlaq",
		arabicTag: "الأَدَبُ وَالأَخْلَاقُ",
		icon: "bi-heart-pulse",
		description:
			"Purification of the spiritual heart (Tazkiyat al-Nafs), interpersonal etiquette, humility, and practical ethics based on Imam al-Ghazali’s works.",
		detailsLink: "#",
	},
	{
		id: 4,
		title: "Islamic Judicial System & Commercial Law",
		level: "Advanced",
		duration: "12 Weeks",
		modules: "24 Modules",
		instructor: "Dr. Tariq Mansoor",
		avatar: "TM",
		category: "Judicial Laws (Fiqh)",
		arabicTag: "الفِقْهُ وَالقَضَاءُ",
		icon: "bi-bank",
		description:
			"Comparative study of classical court procedures (Qada'), evidence evaluation, contract law (Mu'amalat), and contemporary financial ethics.",
		detailsLink: "#",
	},
	{
		id: 5,
		title: "Seerah: Analytical Study of the Life of the Prophet",
		level: "Beginner",
		duration: "8 Weeks",
		modules: "16 Modules",
		instructor: "Shaykh Farooq Khan",
		avatar: "FK",
		category: "History (Tarikh)",
		arabicTag: "السِّيرَةُ النَّبَوِيَّةُ",
		icon: "bi-stars",
		description:
			"Lessons from the Meccan and Medinan periods, strategic leadership, societal transformation, and character study (Shama'il).",
		detailsLink: "#",
	},
	{
		id: 6,
		title: "Ulum al-Quran: Methodology of Exegesis (Tafsir)",
		level: "Intermediate",
		duration: "9 Weeks",
		modules: "18 Modules",
		instructor: "Dr. Maryam Al-Attas",
		avatar: "MA",
		category: "Fundamentals & Aqeedah",
		arabicTag: "عُلُومُ القُرْآنِ",
		icon: "bi-book-half",
		description:
			"History of Quranic compilation, Asbab al-Nuzul (revelation contexts), abrogation (Naskh), and comparing classical Tafsir schools.",
		detailsLink: "#",
	},
];

export const apiHadithBooks = [
	{
		id: 1,
		name: "صحيح البخاري",
		slug: "sahih-bukhari",
		abbreviation: "SB",
		writer: "محمد بن إسماعيل البخاري",
		status: "sahih",
		group: "Kutub al-Sittah",
		life_span: "194-256 AH",
		chapter_count: 99,
		hadith_count: 7276,
		translations: [
			{
				id: 1,
				hadith_book_id: 1,
				lang: "en",
				name: "Sahih al-Bukhari",
				writer: "Muhammad ibn Ismail al Bukhari",
				description:
					"The most authentic book after the Quran, arranged by legal & theological topics.",
			},
			{
				id: 2,
				hadith_book_id: 1,
				lang: "ar",
				name: "صحيح البخاري",
				writer: "محمد بن إسماعيل البخاري",
				description: "",
			},
			{
				id: 3,
				hadith_book_id: 1,
				lang: "ml",
				name: "സ്വഹീഹ് അൽ-ബുഖാരി",
				writer: "മുഹമ്മദ് ബിൻ ഇസ്മായിൽ അൽ ബുഖാരി",
				description: "",
			},
		],
	},
	{
		id: 2,
		name: "صحيح مسلم",
		slug: "sahih-muslim",
		abbreviation: "SM",
		writer: "مسلم بن الحجاج النيسابوري",
		status: "sahih",
		group: "Kutub al-Sittah",
		life_span: "204-261 AH",
		chapter_count: 56,
		hadith_count: 7564,
		translations: [
			{
				id: 4,
				hadith_book_id: 2,
				lang: "en",
				name: "Sahih Muslim",
				writer: "Muslim ibn al-Hajjaj al-Naysaburi",
				description:
					"Renowned for its rigorous thematic organization and preservation of narration variants.",
			},
			{
				id: 5,
				hadith_book_id: 2,
				lang: "ar",
				name: "صحيح مسلم",
				writer: "مسلم بن الحجاج النيسابوري",
				description: "",
			},
			{
				id: 6,
				hadith_book_id: 2,
				lang: "ml",
				name: "സഹീഹ് മുസ്ലിം",
				writer: "മുസ്ലീം ഇബ്നു അൽ-ഹജ്ജാജ് അൽ-നൈസബൂരി",
				description: "",
			},
		],
	},
	{
		id: 4,
		name: "جامع الترمذي",
		slug: "al-tirmidhi",
		abbreviation: "JAT",
		writer: "أبو عيسى محمد بن عيسى الترمذي",
		status: "jami",
		group: "Kutub al-Sittah",
		life_span: "209-279 AH",
		chapter_count: 50,
		hadith_count: 3956,
		translations: [
			{
				id: 7,
				hadith_book_id: 4,
				lang: "en",
				name: "Jami Al-Tirmidhi",
				writer: "Abu Isa Muhammad ibn Isa al-Tirmidhi",
				description:
					"Renowned for grading Hadith gradations (Sahih, Hasan, Da'if) and noting jurisprudential differences.",
			},
			{
				id: 8,
				hadith_book_id: 4,
				lang: "ar",
				name: "جامع الترمذي",
				writer: "أبو عيسى محمد بن عيسى الترمذي",
				description: "",
			},
			{
				id: 9,
				hadith_book_id: 4,
				lang: "ml",
				name: "ജാമി അൽ-തിർമിധി",
				writer: "അബു ഈസാ മുഹമ്മദ് ഇബ്നു ഈസാ അൽ-തിർമിദി",
				description: "",
			},
		],
	},
	{
		id: 5,
		name: "سنن أبو داود",
		slug: "abu-dawood",
		abbreviation: "SAD",
		writer: "أبو داود سليمان بن الأشعث السجستاني",
		status: "sunan",
		group: "Kutub al-Sittah",
		life_span: "202-275 AH",
		chapter_count: 43,
		hadith_count: 5274,
		translations: [
			{
				id: 10,
				hadith_book_id: 5,
				lang: "en",
				name: "Sunan Abu Dawood",
				writer: "Abu Dawud Sulayman ibn al-Ash'ath al-Sijistani",
				description:
					"Centered heavily upon legal rulings (Ahkam) and legislative traditions.",
			},
			{
				id: 11,
				hadith_book_id: 5,
				lang: "ar",
				name: "سنن أبو داود",
				writer: "أبو داود سليمان بن الأشعث السجستاني",
				description: "",
			},
			{
				id: 12,
				hadith_book_id: 5,
				lang: "ml",
				name: "സുനാൻ അബു ദാവൂദ്",
				writer: "അബു ദാവൂദ് സുലൈമാൻ ഇബ്നു അൽ-അശ്അത്ത് അൽ-സിജിസ്ഥാനി",
				description: "",
			},
		],
	},
	{
		id: 6,
		name: "سنن ابن ماجه",
		slug: "ibn-e-majah",
		abbreviation: "SIM",
		writer: "محمد بن يزيد بن ماجه",
		status: "sunan",
		group: "Kutub al-Sittah",
		life_span: "209-273 AH",
		chapter_count: 39,
		hadith_count: 4341,
		translations: [
			{
				id: 13,
				hadith_book_id: 6,
				lang: "en",
				name: "Sunan Ibn Majah",
				writer: "Muhammad ibn Yazīd Ibn Majah",
				description:
					"Features clear legal structure with numerous unique narrations (Zawa'id).",
			},
			{
				id: 14,
				hadith_book_id: 6,
				lang: "ar",
				name: "سنن ابن ماجه",
				writer: "محمد بن يزيد بن ماجه",
				description: "",
			},
			{
				id: 15,
				hadith_book_id: 6,
				lang: "ml",
				name: "സുനാൻ ഇബ്ൻ മാജഹ്",
				writer: "മുഹമ്മദ് ബിൻ യസീദ് ഇബ്ന് മാജഹ്",
				description: "",
			},
		],
	},
	{
		id: 7,
		name: "سنن النسائي",
		slug: "sunan-nasai",
		abbreviation: "SAN",
		writer: "أحمد بن شعيب النسائي",
		status: "sunan",
		group: "Kutub al-Sittah",
		life_span: "214-303 AH",
		chapter_count: 52,
		hadith_count: 5761,
		translations: [
			{
				id: 16,
				hadith_book_id: 7,
				lang: "en",
				name: "Sunan an-Nasa'i",
				writer: "Ahmad ibn Shu'ayb al-Nasa'i",
				description:
					"Distinguished by strict authentication criteria second only to the two Sahihs.",
			},
			{
				id: 17,
				hadith_book_id: 7,
				lang: "ar",
				name: "سنن النسائي",
				writer: "أحمد بن شعيب النسائي",
				description: "",
			},
			{
				id: 18,
				hadith_book_id: 7,
				lang: "ml",
				name: "സുനാൻ അൽ-നസാഈ",
				writer: "അഹ്മദ് ഇബ്നു ശുഐബ് അൽ-നസാഇ",
				description: "",
			},
		],
	},
	{
		id: 8,
		name: "مشکاة المصابیح",
		slug: "mishkat",
		abbreviation: "MAM",
		writer: "محمد بن عبد الله الخطيب التبريزي",
		status: "collection",
		group: "Thematic",
		life_span: "d. 741 AH",
		chapter_count: 29,
		hadith_count: 6293,
		translations: [
			{
				id: 19,
				hadith_book_id: 8,
				lang: "en",
				name: "Mishkat al-Masabih",
				writer: "Muhammad ibn Abdallah al-Khatib al-Tabrizi",
				description:
					"Mishkat al-Masabih is a comprehensive hadith collection that brings together narrations on faith, worship, manners, virtues, and various aspects of Islamic life, organized thematically.",
			},
			{
				id: 20,
				hadith_book_id: 8,
				lang: "ar",
				name: "مشکاة المصابیح",
				writer: "محمد بن عبد الله الخطيب التبريزي",
				description: "",
			},
			{
				id: 21,
				hadith_book_id: 8,
				lang: "ml",
				name: "മിഷ്കാത്ത് അൽ-മസാബിഹ്",
				writer: "മുഹമ്മദ് ഇബ്ൻ അബ്ദല്ല അൽ ഖത്തീബ് അൽ തബ്രിസി",
				description: "",
			},
		],
	},
	{
		id: 9,
		name: "المواطأ",
		slug: "muwatta-malik",
		abbreviation: "MW",
		writer: "مالك بن أنس",
		status: "muwatta",
		group: "Kutub al-Tis'ah",
		life_span: "93-179 AH",
		chapter_count: 61,
		hadith_count: 1985,
		translations: [
			{
				id: 22,
				hadith_book_id: 9,
				lang: "en",
				name: "The Muwaṭṭa",
				writer: "Imam Malik ibn Anas",
				description:
					"Islamic jurisprudence, worship, transactions, manners, and Prophetic traditions.",
			},
			{
				id: 23,
				hadith_book_id: 9,
				lang: "ar",
				name: "المواطأ",
				writer: "مالك بن أنس",
				description: "",
			},
			{
				id: 24,
				hadith_book_id: 9,
				lang: "ml",
				name: "അൽ-മുവത്ത",
				writer: "മാലിക് ഇബ്നു അനസ്",
				description: "",
			},
		],
	},
	{
		id: 10,
		name: "مُسْنَد أَحْمَد بْن حَنْبَل",
		slug: "musnad-ahmad-ibn-hanbal",
		abbreviation: "MAH",
		writer: "اَحْمَد بْن مُحَمَّد بْن حَنْبَل",
		status: "musnad",
		group: "Kutub al-Tis'ah",
		life_span: "164-241 AH",
		chapter_count: 8,
		hadith_count: 1374,
		translations: [
			{
				id: 25,
				hadith_book_id: 10,
				lang: "en",
				name: "Musnad Ahmad ibn Hanbal",
				writer: "Ahmad ibn Muhammad ibn Hanbal",
				description:
					"Hadith collection arranged primarily according to the Companion narrator, rather than by fiqh subject.",
			},
			{
				id: 26,
				hadith_book_id: 10,
				lang: "ar",
				name: "مُسْنَد أَحْمَد بْن حَنْبَل",
				writer: "اَحْمَد بْن مُحَمَّد بْن حَنْبَل",
				description: "",
			},
			{
				id: 27,
				hadith_book_id: 10,
				lang: "ml",
				name: "മുസ്നാദ് അഹ്മദ് ഇബ്ന് ഹന്ബൽ",
				writer: "അഹ്മദ് ഇബ്നു മുഹമ്മദ് ഇബ്ന് ഹന്ബൽ",
				description: "",
			},
		],
	},
	{
		id: 11,
		name: "سنن الدارمي",
		slug: "sunan-al-darimi",
		abbreviation: "SD",
		writer: "عبد الله بن عبد الرحمن الدارمي",
		status: "sunan",
		group: "Kutub al-Tis'ah",
		life_span: "181-255 AH",
		chapter_count: 24,
		hadith_count: 3406,
		translations: [
			{
				id: 28,
				hadith_book_id: 11,
				lang: "en",
				name: "Sunan al-Darimi",
				writer: "Abdullah ibn Abd al-Rahman al-Darimi",
				description:
					"A major hadith collection arranged by subject, covering jurisprudence, worship, manners, and other aspects of the Sunnah.",
			},
			{
				id: 29,
				hadith_book_id: 11,
				lang: "ar",
				name: "سنن الدارمي",
				writer: "عبد الله بن عبد الرحمن الدارمي",
				description: "",
			},
			{
				id: 30,
				hadith_book_id: 11,
				lang: "ml",
				name: "സുനാൻ അൽ-ദാരിമി",
				writer: "അബ്ദുള്ളാ ഇബ്നു അബ്ദുൽ റഹ്മാൻ അൽ-ദാരിമി",
				description: "",
			},
		],
	},
];
